apiVersion: apps/v1
kind: Deployment
metadata:
  name: fractal-frontend
  namespace: xeon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fractal-frontend
  template:
    metadata:
      labels:
        app: fractal-frontend
    spec:
      containers:
      - name: fractal-frontend
        image: europe-west1-docker.pkg.dev/project-45a76f06-067f-40f7-9a4/fractal-repo/fractal-frontend:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: xeon
spec:
  type: LoadBalancer
  selector:
    app: fractal-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80