apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cloud-scaling-demo
data:
  APP_NAME: cloud-scaling-demo-api
  APP_VERSION: "1.0.0"
  APP_ENV: gke-demo
  APP_REGION: europe-west1
  ALLOWED_ORIGINS: "*"
