apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloud-scaling-demo
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: backend
          image: europe-west1-docker.pkg.dev/project-45a76f06-067f-40f7-9a4/cloud-scaling-demo/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6543
              name: http
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: PORT
              value: "6543"
            - name: APP_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          readinessProbe:
            httpGet:
              path: /api/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              cpu: 750m
              memory: 256Mi
