apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: cloud-scaling-demo
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
